name: Rust

on:
  push:
  pull_request:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - name: install cargo-all-features
        uses: baptiste0928/cargo-install@v2.0.0
        with:
          crate: cargo-all-features
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo test-all-features
        env:
          RUST_BACKTRACE: 1
          TG_BOT_KEY: ${{ secrets.TG_BOT_KEY }}

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
  
  doc2readme:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msrd0/cargo-doc2readme
    steps:
    - uses: actions/checkout@v3
    - run: cargo doc2readme --check

  cargo_publish:
    if: ${{ github.event_name == 'release' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: msrd0/cargo-publish-action@v1
        with: 
          packages: my-env-logger-style 
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
